import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: import.meta.dirname })

/**
 * ESLint configuration.
 *
 * Next.js' recommended rules plus the TypeScript layer. Type-aware linting is
 * deliberately not enabled here: `tsc --noEmit` already runs in CI with strict
 * settings, and duplicating that work in ESLint roughly triples lint time for
 * no additional signal.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      // Generated by Next.js on every build; not ours to lint.
      'next-env.d.ts',
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      '.e2e/**',
      '.storage/**',
      'db/migrations/**',
      'design-system/**',
    ],
  },
  {
    rules: {
      // Unused values are almost always a mistake, but an intentionally
      // ignored argument should be expressible.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // `any` erases the guarantees the rest of the codebase depends on.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
]

export default config
