import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, statSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

/**
 * Playwright global setup.
 *
 * Two jobs, both of which must happen before the first test runs:
 *
 *  1. Migrate the E2E database, so the suite runs against the current schema.
 *  2. Produce the resume PDF the tests upload. It is generated by the
 *     application's own renderer rather than committed as a binary, so the
 *     fixture can never drift from what the product actually produces.
 *
 * Before the first *test*, not before the web server: Playwright starts
 * `webServer` first and runs this afterwards. The server therefore boots
 * against an unmigrated database, which is harmless — connections are made per
 * query, and no query happens until a test does. It does mean `webServer.url`
 * cannot point at anything that requires the schema, or the run deadlocks.
 *
 * Child processes invoke `node` directly rather than going through `npx`. On
 * Windows `npx` runs via `cmd`, which swallowed a failing exit code and let
 * setup "succeed" while producing no fixture — the tests then failed much later
 * with a confusing missing-file error. Every step here is verified explicitly.
 */

export const FIXTURE_PDF = resolve(process.cwd(), '.e2e/fixtures/resume.pdf')

/**
 * tsx's CLI entry point, so setup scripts run without a build step.
 *
 * Resolved from the working directory rather than with `import.meta.url`:
 * Playwright loads this file as CommonJS, where `import.meta` is unavailable.
 */
function tsxCli(): string {
  return resolve(process.cwd(), 'node_modules/tsx/dist/cli.mjs')
}

export default function globalSetup(): void {
  const databaseUrl =
    process.env.E2E_DATABASE_URL ?? 'postgresql://rolefit:rolefit@localhost:5433/rolefit_e2e'

  mkdirSync(dirname(FIXTURE_PDF), { recursive: true })

  const runScript = (
    script: string,
    args: string[] = [],
    extraEnv: Record<string, string> = {},
  ): void => {
    try {
      execFileSync(process.execPath, [tsxCli(), script, ...args], {
        stdio: 'inherit',
        env: { ...process.env, DATABASE_URL: databaseUrl, ...extraEnv },
      })
    } catch (error) {
      throw new Error(
        `E2E setup step failed: ${script}\n` +
          `Is PostgreSQL running? Try: npm run db:up\n` +
          `${String(error)}`,
      )
    }
  }

  runScript('scripts/wait-for-db.ts')
  runScript('scripts/migrate.ts')

  // The PDF renderer is a `server-only` module, so the child process needs
  // React's `react-server` export condition — the same one Next.js uses.
  runScript('tests/e2e/setup/make-fixture.ts', [FIXTURE_PDF], {
    NODE_OPTIONS: '--conditions=react-server',
  })

  if (!existsSync(FIXTURE_PDF) || statSync(FIXTURE_PDF).size < 1000) {
    throw new Error(`E2E setup did not produce a usable fixture at ${FIXTURE_PDF}`)
  }
}
